version: '3.8'

services:
  embylens:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: embylens
    ports:
      - "6565:6565"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/embylens.db
      - TZ=Asia/Shanghai
    network_mode: bridge
    restart: always
