version: '3.8'

services:
  lens:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lens
    ports:
      - "6565:6565"
    volumes:
      - ./data:/app/data
      - /vol1/1000/NVME:/vol1/1000/NVME
    user: root
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/lens.db
      - TZ=Asia/Shanghai
    network_mode: bridge
    restart: always
