
services:
  lens:
    image: pipi20xx/lens:latest
    container_name: lens
    ports:
      - "6565:6565"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/lens.db
      - TZ=Asia/Shanghai
    network_mode: bridge
    restart: always
